using MediatR;
using Propel.Modules.Admin.Dtos;
using Propel.Modules.Admin.Enums;

namespace Propel.Modules.Admin.Commands;

/// <summary>
/// Staff walk-in booking command for <c>POST /api/staff/walkin</c> (US_026, AC-2, AC-3).
/// <para>
/// <see cref="StaffId"/> is resolved from JWT claims in the controller — never from the
/// request body (OWASP A01 — Broken Access Control).
/// </para>
/// <list type="bullet">
///   <item><b><see cref="WalkInMode.Link"/></b>: <see cref="PatientId"/> must be supplied.</item>
///   <item><b><see cref="WalkInMode.Create"/></b>: <see cref="Name"/> and <see cref="Email"/> required;
///         <see cref="ContactNumber"/> optional. Duplicate email → HTTP 409.</item>
///   <item><b><see cref="WalkInMode.Anonymous"/></b>: No patient fields required. <c>anonymousVisitId</c>
///         is generated by the handler.</item>
/// </list>
/// Validated by <see cref="Propel.Modules.Admin.Validators.CreateWalkInValidator"/> before the handler executes.
/// </summary>
public sealed record CreateWalkInCommand(
    WalkInMode Mode,
    Guid? PatientId,
    string? Name,
    string? ContactNumber,
    string? Email,
    Guid SpecialtyId,
    DateOnly Date,
    TimeOnly? TimeSlotStart,
    TimeOnly? TimeSlotEnd,
    Guid StaffId,
    string? IpAddress,
    string? CorrelationId
) : IRequest<WalkInResponseDto>;
